/*******************************************************************************
 * UNSTRUCTURED DATA - COMPLETE DEPLOYMENT SCRIPT
 * 
 * This script deploys the entire unstructured data infrastructure:
 * 1. Schema and stages
 * 2. Tables for documents, images, and CV detections
 * 3. Load sample data (maintenance logs, technical manuals, visual inspections)
 * 4. Set up Cortex Search services
 * 5. Create NLP feature extraction views
 * 
 * Run this in Snowsight after uploading documents to stages
 ******************************************************************************/

USE DATABASE UTILITIES_GRID_RELIABILITY;
USE WAREHOUSE COMPUTE_WH;
USE ROLE ACCOUNTADMIN;

-- =============================================================================
-- STEP 1: CREATE UNSTRUCTURED SCHEMA AND STAGES
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS UNSTRUCTURED
    COMMENT = 'Schema for unstructured data: documents, images, videos';

USE SCHEMA UNSTRUCTURED;

-- Stages for document storage
CREATE OR REPLACE STAGE MAINTENANCE_DOCS_STAGE
    COMMENT = 'Storage for maintenance logs, inspection reports, and field notes'
    DIRECTORY = (ENABLE = TRUE);

CREATE OR REPLACE STAGE TECHNICAL_MANUALS_STAGE
    COMMENT = 'Storage for equipment manuals, procedures, and technical specs'
    DIRECTORY = (ENABLE = TRUE);

CREATE OR REPLACE STAGE VISUAL_INSPECTION_STAGE
    COMMENT = 'Storage for inspection photos, videos, thermal images, LiDAR'
    DIRECTORY = (ENABLE = TRUE);

SELECT 'Stages created successfully' as STATUS;

-- =============================================================================
-- STEP 2: CREATE TABLES
-- =============================================================================

-- Maintenance Log Documents
CREATE OR REPLACE TABLE MAINTENANCE_LOG_DOCUMENTS (
    DOCUMENT_ID VARCHAR(50) PRIMARY KEY,
    ASSET_ID VARCHAR(50) NOT NULL,
    DOCUMENT_TYPE VARCHAR(50),
    DOCUMENT_DATE DATE NOT NULL,
    TECHNICIAN_NAME VARCHAR(100),
    TECHNICIAN_ID VARCHAR(50),
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_SIZE_BYTES NUMBER(12),
    FILE_FORMAT VARCHAR(20),
    UPLOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MAINTENANCE_TYPE VARCHAR(50),
    DURATION_HOURS NUMBER(6,2),
    COST_USD NUMBER(12,2),
    FAILURE_OCCURRED BOOLEAN,
    DOCUMENT_TEXT VARCHAR(16777216),
    SUMMARY VARCHAR(5000),
    ROOT_CAUSE_KEYWORDS ARRAY,
    SEVERITY_LEVEL VARCHAR(20),
    RECOMMENDED_ACTIONS ARRAY,
    PARTS_MENTIONED ARRAY,
    PROCESSED_BY_CORTEX BOOLEAN DEFAULT FALSE,
    LAST_PROCESSED_TIMESTAMP TIMESTAMP_NTZ,
    FOREIGN KEY (ASSET_ID) REFERENCES RAW.ASSET_MASTER(ASSET_ID)
);

-- Technical Manuals
CREATE OR REPLACE TABLE TECHNICAL_MANUALS (
    MANUAL_ID VARCHAR(50) PRIMARY KEY,
    MANUAL_TYPE VARCHAR(50),
    EQUIPMENT_TYPE VARCHAR(50),
    MANUFACTURER VARCHAR(100),
    MODEL VARCHAR(100),
    VERSION VARCHAR(20),
    PUBLICATION_DATE DATE,
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_SIZE_BYTES NUMBER(12),
    PAGE_COUNT NUMBER(6),
    UPLOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DOCUMENT_TEXT VARCHAR(16777216),
    TABLE_OF_CONTENTS ARRAY,
    KEY_SPECIFICATIONS OBJECT,
    APPLICABLE_TO_ASSETS ARRAY,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Visual Inspections
CREATE OR REPLACE TABLE VISUAL_INSPECTIONS (
    INSPECTION_ID VARCHAR(50) PRIMARY KEY,
    ASSET_ID VARCHAR(50) NOT NULL,
    INSPECTION_DATE DATE NOT NULL,
    INSPECTOR_NAME VARCHAR(100),
    INSPECTOR_ID VARCHAR(50),
    INSPECTION_METHOD VARCHAR(50),
    WEATHER_CONDITIONS VARCHAR(100),
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_TYPE VARCHAR(20),
    FILE_SIZE_BYTES NUMBER(12),
    UPLOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLUTION VARCHAR(20),
    GPS_LATITUDE NUMBER(10,7),
    GPS_LONGITUDE NUMBER(10,7),
    CV_PROCESSED BOOLEAN DEFAULT FALSE,
    CV_PROCESSING_TIMESTAMP TIMESTAMP_NTZ,
    FOREIGN KEY (ASSET_ID) REFERENCES RAW.ASSET_MASTER(ASSET_ID)
);

-- Computer Vision Detections
CREATE OR REPLACE TABLE CV_DETECTIONS (
    DETECTION_ID VARCHAR(50) PRIMARY KEY,
    INSPECTION_ID VARCHAR(50) NOT NULL,
    ASSET_ID VARCHAR(50) NOT NULL,
    DETECTION_TYPE VARCHAR(50),
    CONFIDENCE_SCORE NUMBER(5,4),
    BOUNDING_BOX OBJECT,
    SEVERITY_LEVEL VARCHAR(20),
    REQUIRES_IMMEDIATE_ACTION BOOLEAN,
    DETECTED_AT_COMPONENT VARCHAR(100),
    DESCRIPTION VARCHAR(1000),
    MODEL_NAME VARCHAR(100),
    MODEL_VERSION VARCHAR(20),
    DETECTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (INSPECTION_ID) REFERENCES VISUAL_INSPECTIONS(INSPECTION_ID),
    FOREIGN KEY (ASSET_ID) REFERENCES RAW.ASSET_MASTER(ASSET_ID)
);

SELECT 'Tables created successfully' as STATUS;

-- =============================================================================
-- STEP 3: CREATE ENRICHED FEATURE VIEW
-- =============================================================================

CREATE OR REPLACE VIEW VW_ENRICHED_ASSET_FEATURES AS
SELECT 
    a.ASSET_ID,
    a.ASSET_TYPE,
    a.MANUFACTURER,
    a.MODEL,
    a.AGE_YEARS,
    a.CRITICALITY_SCORE,
    
    -- Maintenance history (structured)
    COUNT(DISTINCT m.RECORD_ID) as TOTAL_MAINTENANCE_COUNT,
    SUM(m.COST) as TOTAL_MAINTENANCE_COST,
    
    -- Maintenance logs (unstructured - text features)
    COUNT(DISTINCT ml.DOCUMENT_ID) as INSPECTION_REPORT_COUNT,
    SUM(CASE WHEN ml.FAILURE_OCCURRED THEN 1 ELSE 0 END) as DOCUMENTED_FAILURE_COUNT,
    MAX(ml.DOCUMENT_DATE) as LAST_INSPECTION_DATE,
    DATEDIFF(day, MAX(ml.DOCUMENT_DATE), CURRENT_DATE()) as DAYS_SINCE_LAST_INSPECTION,
    
    -- Visual inspections (computer vision features)
    COUNT(DISTINCT vi.INSPECTION_ID) as VISUAL_INSPECTION_COUNT,
    COUNT(DISTINCT cv.DETECTION_ID) as TOTAL_CV_DETECTIONS,
    SUM(CASE WHEN cv.SEVERITY_LEVEL = 'CRITICAL' THEN 1 ELSE 0 END) as CRITICAL_VISUAL_ISSUES,
    SUM(CASE WHEN cv.SEVERITY_LEVEL = 'HIGH' THEN 1 ELSE 0 END) as HIGH_VISUAL_ISSUES,
    SUM(CASE WHEN cv.DETECTION_TYPE = 'CORROSION' THEN 1 ELSE 0 END) as CORROSION_DETECTIONS,
    SUM(CASE WHEN cv.DETECTION_TYPE = 'LEAK' THEN 1 ELSE 0 END) as LEAK_DETECTIONS,
    SUM(CASE WHEN cv.DETECTION_TYPE = 'HOTSPOT' THEN 1 ELSE 0 END) as HOTSPOT_DETECTIONS,
    AVG(cv.CONFIDENCE_SCORE) as AVG_CV_CONFIDENCE,
    MAX(CASE WHEN cv.REQUIRES_IMMEDIATE_ACTION THEN 1 ELSE 0 END) as HAS_URGENT_VISUAL_ISSUE,
    
    -- Latest sensor data
    sr.OIL_TEMPERATURE_C,
    sr.LOAD_CURRENT_A,
    sr.VIBRATION_MM_S
    
FROM RAW.ASSET_MASTER a
LEFT JOIN RAW.MAINTENANCE_HISTORY m ON a.ASSET_ID = m.ASSET_ID
LEFT JOIN MAINTENANCE_LOG_DOCUMENTS ml ON a.ASSET_ID = ml.ASSET_ID
LEFT JOIN VISUAL_INSPECTIONS vi ON a.ASSET_ID = vi.ASSET_ID
LEFT JOIN CV_DETECTIONS cv ON a.ASSET_ID = cv.ASSET_ID
LEFT JOIN (
    SELECT ASSET_ID, 
           OIL_TEMPERATURE_C, 
           LOAD_CURRENT_A, 
           VIBRATION_MM_S,
           ROW_NUMBER() OVER (PARTITION BY ASSET_ID ORDER BY READING_TIMESTAMP DESC) as rn
    FROM RAW.SENSOR_READINGS
) sr ON a.ASSET_ID = sr.ASSET_ID AND sr.rn = 1
WHERE a.STATUS = 'ACTIVE'
GROUP BY 
    a.ASSET_ID, a.ASSET_TYPE, a.MANUFACTURER, a.MODEL, a.AGE_YEARS, 
    a.CRITICALITY_SCORE, sr.OIL_TEMPERATURE_C, sr.LOAD_CURRENT_A, sr.VIBRATION_MM_S;

SELECT 'Enriched features view created' as STATUS;

-- =============================================================================
-- STEP 4: GRANT PERMISSIONS
-- =============================================================================

GRANT USAGE ON SCHEMA UNSTRUCTURED TO ROLE GRID_ANALYST;
GRANT USAGE ON SCHEMA UNSTRUCTURED TO ROLE GRID_DATA_ENGINEER;
GRANT USAGE ON SCHEMA UNSTRUCTURED TO ROLE GRID_ML_ENGINEER;

GRANT READ, WRITE ON STAGE MAINTENANCE_DOCS_STAGE TO ROLE GRID_DATA_ENGINEER;
GRANT READ, WRITE ON STAGE TECHNICAL_MANUALS_STAGE TO ROLE GRID_DATA_ENGINEER;
GRANT READ, WRITE ON STAGE VISUAL_INSPECTION_STAGE TO ROLE GRID_DATA_ENGINEER;

GRANT READ ON STAGE MAINTENANCE_DOCS_STAGE TO ROLE GRID_ANALYST;
GRANT READ ON STAGE TECHNICAL_MANUALS_STAGE TO ROLE GRID_ANALYST;

GRANT SELECT ON ALL TABLES IN SCHEMA UNSTRUCTURED TO ROLE GRID_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA UNSTRUCTURED TO ROLE GRID_ANALYST;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA UNSTRUCTURED TO ROLE GRID_DATA_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA UNSTRUCTURED TO ROLE GRID_DATA_ENGINEER;

GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA UNSTRUCTURED TO ROLE GRID_ML_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA UNSTRUCTURED TO ROLE GRID_ML_ENGINEER;

SELECT 'Permissions granted' as STATUS;

-- =============================================================================
-- STEP 5: VERIFICATION QUERIES
-- =============================================================================

SELECT 'Schema and Infrastructure Complete!' as STATUS;
SELECT '✓ 3 Stages created' as INFO;
SELECT '✓ 4 Tables created' as INFO;
SELECT '✓ 1 Enriched view created' as INFO;
SELECT '✓ Permissions granted' as INFO;

-- Show objects
SHOW STAGES IN SCHEMA UNSTRUCTURED;
SHOW TABLES IN SCHEMA UNSTRUCTURED;
SHOW VIEWS IN SCHEMA UNSTRUCTURED;

-- =============================================================================
-- NEXT STEPS (Manual):
-- =============================================================================

/*
1. UPLOAD DOCUMENTS TO STAGES:
   - PUT file:///path/to/generated_maintenance_logs/*.pdf @MAINTENANCE_DOCS_STAGE;
   - PUT file:///path/to/generated_technical_manuals/*.pdf @TECHNICAL_MANUALS_STAGE;
   
2. LOAD METADATA:
   - Run load_unstructured_data.sql to populate tables
   
3. SET UP CORTEX SEARCH:
   - Run setup_cortex_search.sql
   
4. UPDATE INTELLIGENCE AGENT:
   - Run update_intelligence_agent.sql
   
5. VERIFY DATA:
   SELECT COUNT(*) FROM MAINTENANCE_LOG_DOCUMENTS;
   SELECT COUNT(*) FROM TECHNICAL_MANUALS;
   SELECT COUNT(*) FROM VISUAL_INSPECTIONS;
   SELECT COUNT(*) FROM CV_DETECTIONS;
*/

