/*******************************************************************************
 * LOAD UNSTRUCTURED DATA
 * 
 * This script loads metadata for all unstructured data:
 * - Maintenance log documents
 * - Technical manuals
 * - Visual inspections
 * - Computer vision detections
 * 
 * Prerequisites: Run deploy_all_unstructured.sql first
 ******************************************************************************/

USE DATABASE UTILITIES_GRID_RELIABILITY;
USE SCHEMA UNSTRUCTURED;
USE WAREHOUSE COMPUTE_WH;

-- =============================================================================
-- Load Maintenance Log Documents Metadata
-- =============================================================================

-- This would be populated from the generated JSON file
-- For demo, insert a few samples to show the structure

INSERT INTO MAINTENANCE_LOG_DOCUMENTS (
    DOCUMENT_ID, ASSET_ID, DOCUMENT_TYPE, DOCUMENT_DATE, TECHNICIAN_NAME, TECHNICIAN_ID,
    FILE_PATH, FILE_SIZE_BYTES, FILE_FORMAT, MAINTENANCE_TYPE, DURATION_HOURS, COST_USD,
    FAILURE_OCCURRED, DOCUMENT_TEXT, SUMMARY, ROOT_CAUSE_KEYWORDS, SEVERITY_LEVEL, RECOMMENDED_ACTIONS
) 
SELECT 
    $1:DOCUMENT_ID::VARCHAR as DOCUMENT_ID,
    $1:ASSET_ID::VARCHAR as ASSET_ID,
    $1:DOCUMENT_TYPE::VARCHAR as DOCUMENT_TYPE,
    $1:DOCUMENT_DATE::DATE as DOCUMENT_DATE,
    $1:TECHNICIAN_NAME::VARCHAR as TECHNICIAN_NAME,
    $1:TECHNICIAN_ID::VARCHAR as TECHNICIAN_ID,
    $1:FILE_PATH::VARCHAR as FILE_PATH,
    $1:FILE_SIZE_BYTES::NUMBER as FILE_SIZE_BYTES,
    $1:FILE_FORMAT::VARCHAR as FILE_FORMAT,
    $1:MAINTENANCE_TYPE::VARCHAR as MAINTENANCE_TYPE,
    $1:DURATION_HOURS::NUMBER as DURATION_HOURS,
    $1:COST_USD::NUMBER as COST_USD,
    $1:FAILURE_OCCURRED::BOOLEAN as FAILURE_OCCURRED,
    $1:DOCUMENT_TEXT::VARCHAR as DOCUMENT_TEXT,
    LEFT($1:DOCUMENT_TEXT::VARCHAR, 500) as SUMMARY,
    PARSE_JSON($1:ROOT_CAUSE_KEYWORDS) as ROOT_CAUSE_KEYWORDS,
    $1:SEVERITY_LEVEL::VARCHAR as SEVERITY_LEVEL,
    PARSE_JSON($1:RECOMMENDED_ACTIONS) as RECOMMENDED_ACTIONS
FROM @MAINTENANCE_DOCS_STAGE/../generated_maintenance_logs/maintenance_logs_metadata.json
(FILE_FORMAT => (TYPE = 'JSON'));

SELECT COUNT(*) as MAINTENANCE_LOGS_LOADED FROM MAINTENANCE_LOG_DOCUMENTS;

-- =============================================================================
-- Load Technical Manuals Metadata
-- =============================================================================

INSERT INTO TECHNICAL_MANUALS (
    MANUAL_ID, MANUAL_TYPE, EQUIPMENT_TYPE, MANUFACTURER, MODEL, VERSION,
    PUBLICATION_DATE, FILE_PATH, FILE_SIZE_BYTES, PAGE_COUNT
)
SELECT 
    $1:MANUAL_ID::VARCHAR as MANUAL_ID,
    $1:MANUAL_TYPE::VARCHAR as MANUAL_TYPE,
    $1:EQUIPMENT_TYPE::VARCHAR as EQUIPMENT_TYPE,
    $1:MANUFACTURER::VARCHAR as MANUFACTURER,
    $1:MODEL::VARCHAR as MODEL,
    $1:VERSION::VARCHAR as VERSION,
    $1:PUBLICATION_DATE::DATE as PUBLICATION_DATE,
    $1:FILE_PATH::VARCHAR as FILE_PATH,
    $1:FILE_SIZE_BYTES::NUMBER as FILE_SIZE_BYTES,
    $1:PAGE_COUNT::NUMBER as PAGE_COUNT
FROM @TECHNICAL_MANUALS_STAGE/../generated_technical_manuals/technical_manuals_metadata.json
(FILE_FORMAT => (TYPE = 'JSON'));

SELECT COUNT(*) as TECHNICAL_MANUALS_LOADED FROM TECHNICAL_MANUALS;

-- =============================================================================
-- Load Visual Inspections
-- =============================================================================

INSERT INTO VISUAL_INSPECTIONS (
    INSPECTION_ID, ASSET_ID, INSPECTION_DATE, INSPECTOR_NAME, INSPECTOR_ID,
    INSPECTION_METHOD, WEATHER_CONDITIONS, FILE_PATH, FILE_TYPE, FILE_SIZE_BYTES,
    RESOLUTION, GPS_LATITUDE, GPS_LONGITUDE, CV_PROCESSED, CV_PROCESSING_TIMESTAMP,
    UPLOAD_TIMESTAMP
)
SELECT 
    $1:INSPECTION_ID::VARCHAR as INSPECTION_ID,
    $1:ASSET_ID::VARCHAR as ASSET_ID,
    $1:INSPECTION_DATE::DATE as INSPECTION_DATE,
    $1:INSPECTOR_NAME::VARCHAR as INSPECTOR_NAME,
    $1:INSPECTOR_ID::VARCHAR as INSPECTOR_ID,
    $1:INSPECTION_METHOD::VARCHAR as INSPECTION_METHOD,
    $1:WEATHER_CONDITIONS::VARCHAR as WEATHER_CONDITIONS,
    $1:FILE_PATH::VARCHAR as FILE_PATH,
    $1:FILE_TYPE::VARCHAR as FILE_TYPE,
    $1:FILE_SIZE_BYTES::NUMBER as FILE_SIZE_BYTES,
    $1:RESOLUTION::VARCHAR as RESOLUTION,
    $1:GPS_LATITUDE::NUMBER as GPS_LATITUDE,
    $1:GPS_LONGITUDE::NUMBER as GPS_LONGITUDE,
    $1:CV_PROCESSED::BOOLEAN as CV_PROCESSED,
    $1:CV_PROCESSING_TIMESTAMP::TIMESTAMP_NTZ as CV_PROCESSING_TIMESTAMP,
    $1:UPLOAD_TIMESTAMP::TIMESTAMP_NTZ as UPLOAD_TIMESTAMP
FROM @VISUAL_INSPECTION_STAGE/../generated_visual_inspections/visual_inspections_metadata.json
(FILE_FORMAT => (TYPE = 'JSON'));

SELECT COUNT(*) as VISUAL_INSPECTIONS_LOADED FROM VISUAL_INSPECTIONS;

-- =============================================================================
-- Load CV Detections
-- =============================================================================

INSERT INTO CV_DETECTIONS (
    DETECTION_ID, INSPECTION_ID, ASSET_ID, DETECTION_TYPE, CONFIDENCE_SCORE,
    BOUNDING_BOX, SEVERITY_LEVEL, REQUIRES_IMMEDIATE_ACTION, DETECTED_AT_COMPONENT,
    DESCRIPTION, MODEL_NAME, MODEL_VERSION, DETECTION_TIMESTAMP
)
SELECT 
    $1:DETECTION_ID::VARCHAR as DETECTION_ID,
    $1:INSPECTION_ID::VARCHAR as INSPECTION_ID,
    $1:ASSET_ID::VARCHAR as ASSET_ID,
    $1:DETECTION_TYPE::VARCHAR as DETECTION_TYPE,
    $1:CONFIDENCE_SCORE::NUMBER as CONFIDENCE_SCORE,
    PARSE_JSON($1:BOUNDING_BOX) as BOUNDING_BOX,
    $1:SEVERITY_LEVEL::VARCHAR as SEVERITY_LEVEL,
    $1:REQUIRES_IMMEDIATE_ACTION::BOOLEAN as REQUIRES_IMMEDIATE_ACTION,
    $1:DETECTED_AT_COMPONENT::VARCHAR as DETECTED_AT_COMPONENT,
    $1:DESCRIPTION::VARCHAR as DESCRIPTION,
    $1:MODEL_NAME::VARCHAR as MODEL_NAME,
    $1:MODEL_VERSION::VARCHAR as MODEL_VERSION,
    $1:DETECTION_TIMESTAMP::TIMESTAMP_NTZ as DETECTION_TIMESTAMP
FROM @VISUAL_INSPECTION_STAGE/../generated_visual_inspections/cv_detections.json
(FILE_FORMAT => (TYPE = 'JSON'));

SELECT COUNT(*) as CV_DETECTIONS_LOADED FROM CV_DETECTIONS;

-- =============================================================================
-- VERIFICATION SUMMARY
-- =============================================================================

SELECT 'DATA LOAD COMPLETE' as STATUS;
SELECT '---------------------------------------------------' as LINE;
SELECT COUNT(*) || ' Maintenance Logs' as LOADED FROM MAINTENANCE_LOG_DOCUMENTS
UNION ALL
SELECT COUNT(*) || ' Technical Manuals' FROM TECHNICAL_MANUALS
UNION ALL
SELECT COUNT(*) || ' Visual Inspections' FROM VISUAL_INSPECTIONS
UNION ALL
SELECT COUNT(*) || ' CV Detections' FROM CV_DETECTIONS;

-- Sample queries to verify data
SELECT '---------------------------------------------------' as LINE;
SELECT 'Sample Maintenance Logs by Type:' as INFO;
SELECT MAINTENANCE_TYPE, COUNT(*) as COUNT
FROM MAINTENANCE_LOG_DOCUMENTS
GROUP BY MAINTENANCE_TYPE
ORDER BY COUNT DESC;

SELECT 'Sample Technical Manuals by Manufacturer:' as INFO;
SELECT MANUFACTURER, COUNT(*) as COUNT
FROM TECHNICAL_MANUALS
GROUP BY MANUFACTURER
ORDER BY COUNT DESC;

SELECT 'Sample CV Detections by Type:' as INFO;
SELECT DETECTION_TYPE, 
       COUNT(*) as TOTAL,
       SUM(CASE WHEN SEVERITY_LEVEL = 'CRITICAL' THEN 1 ELSE 0 END) as CRITICAL_COUNT
FROM CV_DETECTIONS
GROUP BY DETECTION_TYPE
ORDER BY TOTAL DESC;

-- Check enriched features
SELECT 'Sample Enriched Asset Features:' as INFO;
SELECT ASSET_ID,
       INSPECTION_REPORT_COUNT,
       VISUAL_INSPECTION_COUNT,
       TOTAL_CV_DETECTIONS,
       CRITICAL_VISUAL_ISSUES,
       HIGH_VISUAL_ISSUES
FROM VW_ENRICHED_ASSET_FEATURES
WHERE TOTAL_CV_DETECTIONS > 0
LIMIT 10;

