-- Maintenance Logs Chunk 4/6 (records 51-60)
INSERT INTO UTILITIES_GRID_RELIABILITY.UNSTRUCTURED.MAINTENANCE_LOG_DOCUMENTS
(DOCUMENT_ID, ASSET_ID, DOCUMENT_TYPE, DOCUMENT_DATE, TECHNICIAN_NAME, TECHNICIAN_ID,
 FILE_PATH, FILE_SIZE_BYTES, FILE_FORMAT, MAINTENANCE_TYPE, DURATION_HOURS, COST_USD,
 FAILURE_OCCURRED, DOCUMENT_TEXT, SUMMARY, ROOT_CAUSE_KEYWORDS, SEVERITY_LEVEL, RECOMMENDED_ACTIONS)
SELECT 'MAINT-T-SS079-001-20231217-051', 'T-SS079-001', 'INSPECTION_REPORT',
       '2023-12-17'::DATE, 'Emily Davis', 'TECH1837',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS079-001-20231217-051.pdf', 3974, 'PDF',
       'CORRECTIVE', 10.68, 43475.57,
       FALSE, 'Responded to abnormal readings from T-SS079-001. Investigation revealed sustained high load. Overload Condition identified as primary issue. Performed load redistribution. Equipment returned to normal operation. Recommend follow-up inspection in 30 days to verify stability.', 'Responded to abnormal readings from T-SS079-001. Investigation revealed sustained high load. Overload Condition identified as primary issue. Performed load redistribution. Equipment returned to normal operation. Recommend follow-up inspection in 30 days to verify stability.',
       PARSE_JSON('["Overload Condition", "sustained high load", "exceeding nameplate rating"]'), 'HIGH',
       PARSE_JSON('["Load redistribution", "Capacity upgrade", "Parallel operation", "Increase monitoring frequency", "Schedule follow-up in 2 weeks", "Review similar assets"]')
UNION ALL SELECT 'MAINT-T-SS017-001-20240315-052', 'T-SS017-001', 'INSPECTION_REPORT',
       '2024-03-15'::DATE, 'David Rodriguez', 'TECH7861',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS017-001-20240315-052.pdf', 3826, 'PDF',
       'PREVENTIVE', 5.08, 8644.85,
       FALSE, 'Performed routine quarterly inspection of transformer T-SS017-001. Visual inspection showed equipment in satisfactory condition. Oil sample collected for laboratory analysis. All cooling fans operational. Minor paint touch-up applied to tank exterior. No immediate concerns noted.', 'Performed routine quarterly inspection of transformer T-SS017-001. Visual inspection showed equipment in satisfactory condition. Oil sample collected for laboratory analysis. All cooling fans operational. Minor paint touch-up applied to tank exterior. No immediate concerns noted.',
       PARSE_JSON('[]'), 'LOW',
       PARSE_JSON('["Load redistribution", "Capacity upgrade", "Parallel operation", "Continue standard monitoring", "No immediate action required"]')
UNION ALL SELECT 'MAINT-T-SS073-001-20241025-053', 'T-SS073-001', 'INSPECTION_REPORT',
       '2024-10-25'::DATE, 'Lisa Thompson', 'TECH1825',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS073-001-20241025-053.pdf', 3779, 'PDF',
       'INSPECTION', 2.46, 3705.62,
       FALSE, 'Infrared thermal scan completed on T-SS073-001. No hotspots detected. Temperature distribution uniform across all components. This inspection is part of our predictive maintenance program. Results support continued normal operation. Recommend next thermal survey in 6 months.', 'Infrared thermal scan completed on T-SS073-001. No hotspots detected. Temperature distribution uniform across all components. This inspection is part of our predictive maintenance program. Results support continued normal operation. Recommend next thermal survey in 6 months.',
       PARSE_JSON('[]'), 'LOW',
       PARSE_JSON('["Continue routine monitoring", "Continue standard monitoring", "No immediate action required"]')
UNION ALL SELECT 'MAINT-T-SS034-001-20250206-054', 'T-SS034-001', 'INSPECTION_REPORT',
       '2025-02-06'::DATE, 'Maria Lopez', 'TECH2912',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS034-001-20250206-054.pdf', 3828, 'PDF',
       'PREVENTIVE', 2.66, 12188.85,
       FALSE, 'Performed routine quarterly inspection of transformer T-SS034-001. Visual inspection showed equipment in satisfactory condition. Oil sample collected for laboratory analysis. All cooling fans operational. Minor paint touch-up applied to tank exterior. No immediate concerns noted.', 'Performed routine quarterly inspection of transformer T-SS034-001. Visual inspection showed equipment in satisfactory condition. Oil sample collected for laboratory analysis. All cooling fans operational. Minor paint touch-up applied to tank exterior. No immediate concerns noted.',
       PARSE_JSON('[]'), 'LOW',
       PARSE_JSON('["Load redistribution", "Capacity upgrade", "Parallel operation", "Continue standard monitoring", "No immediate action required"]')
UNION ALL SELECT 'MAINT-T-SS045-001-20250519-055', 'T-SS045-001', 'INSPECTION_REPORT',
       '2025-05-19'::DATE, 'David Rodriguez', 'TECH7207',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS045-001-20250519-055.pdf', 3805, 'PDF',
       'INSPECTION', 1.16, 2983.83,
       FALSE, 'Walk-through inspection performed on T-SS045-001. Checked for obvious signs of deterioration or damage. All observed parameters normal. Cooling system functioning properly. No unusual sounds or odors noted. Asset appears to be operating satisfactorily. Documentation updated in asset management system.', 'Walk-through inspection performed on T-SS045-001. Checked for obvious signs of deterioration or damage. All observed parameters normal. Cooling system functioning properly. No unusual sounds or odors noted. Asset appears to be operating satisfactorily. Documentation updated in asset management system.',
       PARSE_JSON('[]'), 'LOW',
       PARSE_JSON('["Continue routine monitoring", "Continue standard monitoring", "No immediate action required"]')
UNION ALL SELECT 'MAINT-T-SS090-001-20250806-056', 'T-SS090-001', 'INSPECTION_REPORT',
       '2025-08-06'::DATE, 'John Martinez', 'TECH7184',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS090-001-20250806-056.pdf', 3993, 'PDF',
       'CORRECTIVE', 5.99, 42740.81,
       FALSE, 'Corrective action taken on T-SS090-001 following operations alert. Found evidence of loose components. Root cause analysis indicates excessive vibration. Implemented replace bearings as remedial measure. Post-repair testing satisfactory. System restored to service.', 'Corrective action taken on T-SS090-001 following operations alert. Found evidence of loose components. Root cause analysis indicates excessive vibration. Implemented replace bearings as remedial measure. Post-repair testing satisfactory. System restored to service.',
       PARSE_JSON('["Excessive Vibration", "abnormal vibration levels", "loose components"]'), 'MEDIUM',
       PARSE_JSON('["Tighten connections", "Replace bearings", "Balance rotating parts", "Monitor trend over next 30 days", "Include in quarterly review", "Document for analysis"]')
UNION ALL SELECT 'MAINT-T-SS015-001-20250204-057', 'T-SS015-001', 'INSPECTION_REPORT',
       '2025-02-04'::DATE, 'Robert Wilson', 'TECH5656',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS015-001-20250204-057.pdf', 3829, 'PDF',
       'PREVENTIVE', 5.2, 11417.02,
       FALSE, 'Performed routine quarterly inspection of transformer T-SS015-001. Visual inspection showed equipment in satisfactory condition. Oil sample collected for laboratory analysis. All cooling fans operational. Minor paint touch-up applied to tank exterior. No immediate concerns noted.', 'Performed routine quarterly inspection of transformer T-SS015-001. Visual inspection showed equipment in satisfactory condition. Oil sample collected for laboratory analysis. All cooling fans operational. Minor paint touch-up applied to tank exterior. No immediate concerns noted.',
       PARSE_JSON('[]'), 'LOW',
       PARSE_JSON('["Clean radiators", "Check oil level", "Inspect cooling fans", "Continue standard monitoring", "No immediate action required"]')
UNION ALL SELECT 'MAINT-T-SS076-001-20240627-058', 'T-SS076-001', 'INSPECTION_REPORT',
       '2024-06-27'::DATE, 'Jennifer Garcia', 'TECH3013',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS076-001-20240627-058.pdf', 3944, 'PDF',
       'CORRECTIVE', 6.55, 23183.56,
       FALSE, 'Responded to abnormal readings from T-SS076-001. Investigation revealed high moisture content. Oil Contamination identified as primary issue. Performed oil filtering. Equipment returned to normal operation. Recommend follow-up inspection in 30 days to verify stability.', 'Responded to abnormal readings from T-SS076-001. Investigation revealed high moisture content. Oil Contamination identified as primary issue. Performed oil filtering. Equipment returned to normal operation. Recommend follow-up inspection in 30 days to verify stability.',
       PARSE_JSON('["Oil Contamination", "high moisture content", "acidic oil"]'), 'MEDIUM',
       PARSE_JSON('["Oil filtering", "Oil replacement", "Seal repair", "Monitor trend over next 30 days", "Include in quarterly review", "Document for analysis"]')
UNION ALL SELECT 'MAINT-T-SS000-001-20251030-059', 'T-SS000-001', 'INSPECTION_REPORT',
       '2025-10-30'::DATE, 'Mike Chen', 'TECH9753',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS000-001-20251030-059.pdf', 4018, 'PDF',
       'EMERGENCY', 6.61, 87433.48,
       TRUE, 'URGENT REPAIR: T-SS000-001 tripped offline unexpectedly. Field investigation found lightning strike. Weather Damage confirmed as failure mode. Significant damage observed. Assess damage underway. Parts ordered for expedited delivery. Customer impact: 12,500 accounts. Working around the clock to restore service.', 'URGENT REPAIR: T-SS000-001 tripped offline unexpectedly. Field investigation found lightning strike. Weather Damage confirmed as failure mode. Significant damage observed. Assess damage underway. Parts ordered for expedited delivery. Customer impact: 12,500 accounts. Working around the clock to restore service.',
       PARSE_JSON('["Weather Damage", "lightning strike", "flood damage"]'), 'MEDIUM',
       PARSE_JSON('["Assess damage", "Dry out equipment", "Replace damaged parts", "Monitor trend over next 30 days", "Include in quarterly review", "Document for analysis"]')
UNION ALL SELECT 'MAINT-T-SS009-001-20231224-060', 'T-SS009-001', 'INSPECTION_REPORT',
       '2023-12-24'::DATE, 'John Martinez', 'TECH5328',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS009-001-20231224-060.pdf', 4025, 'PDF',
       'EMERGENCY', 13.94, 35004.83,
       TRUE, 'URGENT REPAIR: T-SS009-001 tripped offline unexpectedly. Field investigation found elevated oil temperature. Overheating confirmed as failure mode. Significant damage observed. Replace cooling system underway. Parts ordered for expedited delivery. Customer impact: 12,000 accounts. Working around the clock to restore service.', 'URGENT REPAIR: T-SS009-001 tripped offline unexpectedly. Field investigation found elevated oil temperature. Overheating confirmed as failure mode. Significant damage observed. Replace cooling system underway. Parts ordered for expedited delivery. Customer impact: 12,000 accounts. Working around the clock to restore service.',
       PARSE_JSON('["Overheating", "elevated oil temperature", "thermal runaway"]'), 'HIGH',
       PARSE_JSON('["Replace cooling system", "Reduce load", "Add ventilation", "Increase monitoring frequency", "Schedule follow-up in 2 weeks", "Review similar assets"]')
;
