-- Maintenance Logs Chunk 2/6 (records 31-40)
INSERT INTO UTILITIES_GRID_RELIABILITY.UNSTRUCTURED.MAINTENANCE_LOG_DOCUMENTS
(DOCUMENT_ID, ASSET_ID, DOCUMENT_TYPE, DOCUMENT_DATE, TECHNICIAN_NAME, TECHNICIAN_ID,
 FILE_PATH, FILE_SIZE_BYTES, FILE_FORMAT, MAINTENANCE_TYPE, DURATION_HOURS, COST_USD,
 FAILURE_OCCURRED, DOCUMENT_TEXT, SUMMARY, ROOT_CAUSE_KEYWORDS, SEVERITY_LEVEL, RECOMMENDED_ACTIONS)
SELECT 'MAINT-T-SS079-001-20250926-031', 'T-SS079-001', 'INSPECTION_REPORT',
       '2025-09-26'::DATE, 'Lisa Thompson', 'TECH9518',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS079-001-20250926-031.pdf', 3992, 'PDF',
       'CORRECTIVE', 5.91, 39419.54,
       FALSE, 'Corrective action taken on T-SS079-001 following operations alert. Found evidence of moisture ingress. Root cause analysis indicates insulation degradation. Implemented replace bushings as remedial measure. Post-repair testing satisfactory. System restored to service.', 'Corrective action taken on T-SS079-001 following operations alert. Found evidence of moisture ingress. Root cause analysis indicates insulation degradation. Implemented replace bushings as remedial measure. Post-repair testing satisfactory. System restored to service.',
       PARSE_JSON('["Insulation Degradation", "low insulation resistance", "moisture ingress"]'), 'CRITICAL',
       PARSE_JSON('["Oil reclamation", "Replace bushings", "Transformer replacement", "Immediate review by engineering team", "Daily monitoring until stable", "Prepare backup equipment"]')
UNION ALL SELECT 'MAINT-T-SS035-001-20250531-032', 'T-SS035-001', 'INSPECTION_REPORT',
       '2025-05-31'::DATE, 'Chris Anderson', 'TECH2856',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS035-001-20250531-032.pdf', 4007, 'PDF',
       'CORRECTIVE', 8.07, 25176.1,
       TRUE, 'Maintenance crew dispatched to T-SS035-001 for reported issue. Discovered rust on tank surface during inspection. Tank Corrosion confirmed through diagnostic testing. Completed sandblast and repaint. Load tests performed successfully. Placed asset back online with continuous monitoring recommended.', 'Maintenance crew dispatched to T-SS035-001 for reported issue. Discovered rust on tank surface during inspection. Tank Corrosion confirmed through diagnostic testing. Completed sandblast and repaint. Load tests performed successfully. Placed asset back online with continuous monitoring recommended.',
       PARSE_JSON('["Tank Corrosion", "rust on tank surface", "paint deterioration"]'), 'MEDIUM',
       PARSE_JSON('["Sandblast and repaint", "Seal leaks", "Monitor corrosion rate", "Monitor trend over next 30 days", "Include in quarterly review", "Document for analysis"]')
UNION ALL SELECT 'MAINT-T-SS079-001-20240131-033', 'T-SS079-001', 'INSPECTION_REPORT',
       '2024-01-31'::DATE, 'Emily Davis', 'TECH7035',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS079-001-20240131-033.pdf', 3818, 'PDF',
       'PREVENTIVE', 2.23, 7708.98,
       FALSE, 'Performed routine quarterly inspection of transformer T-SS079-001. Visual inspection showed equipment in satisfactory condition. Oil sample collected for laboratory analysis. All cooling fans operational. Minor paint touch-up applied to tank exterior. No immediate concerns noted.', 'Performed routine quarterly inspection of transformer T-SS079-001. Visual inspection showed equipment in satisfactory condition. Oil sample collected for laboratory analysis. All cooling fans operational. Minor paint touch-up applied to tank exterior. No immediate concerns noted.',
       PARSE_JSON('[]'), 'LOW',
       PARSE_JSON('["Assess damage", "Dry out equipment", "Replace damaged parts", "Continue standard monitoring", "No immediate action required"]')
UNION ALL SELECT 'MAINT-T-SS073-001-20240527-034', 'T-SS073-001', 'INSPECTION_REPORT',
       '2024-05-27'::DATE, 'Jennifer Garcia', 'TECH2220',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS073-001-20240527-034.pdf', 3994, 'PDF',
       'EMERGENCY', 23.62, 43932.01,
       TRUE, 'EMERGENCY RESPONSE: T-SS073-001 experienced failure at 21:42. Weather Damage identified as cause. lightning strike was primary factor. Immediate isolation performed. Load transferred to backup transformer. Assess damage required. Estimated repair time: 48-72 hours. 18,000 customers temporarily affected.', 'EMERGENCY RESPONSE: T-SS073-001 experienced failure at 21:42. Weather Damage identified as cause. lightning strike was primary factor. Immediate isolation performed. Load transferred to backup transformer. Assess damage required. Estimated repair time: 48-72 hours. 18,000 customers temporarily affected.',
       PARSE_JSON('["Weather Damage", "lightning strike", "flood damage"]'), 'MEDIUM',
       PARSE_JSON('["Assess damage", "Dry out equipment", "Replace damaged parts", "Monitor trend over next 30 days", "Include in quarterly review", "Document for analysis"]')
UNION ALL SELECT 'MAINT-T-SS096-001-20240414-035', 'T-SS096-001', 'INSPECTION_REPORT',
       '2024-04-14'::DATE, 'Emily Davis', 'TECH7489',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS096-001-20240414-035.pdf', 3856, 'PDF',
       'PREVENTIVE', 3.18, 9321.28,
       FALSE, 'Conducted scheduled preventive maintenance on T-SS096-001. Checked all electrical connections, found all secure. Oil level and color satisfactory. Bushings clean with no signs of tracking. Radiators clean and unobstructed. Load tap changer tested - operating normally. Recommended continued monitoring.', 'Conducted scheduled preventive maintenance on T-SS096-001. Checked all electrical connections, found all secure. Oil level and color satisfactory. Bushings clean with no signs of tracking. Radiators clean and unobstructed. Load tap changer tested - operating normally. Recommended continued monitoring.',
       PARSE_JSON('[]'), 'LOW',
       PARSE_JSON('["Oil reclamation", "Replace bushings", "Transformer replacement", "Continue standard monitoring", "No immediate action required"]')
UNION ALL SELECT 'MAINT-T-SS058-001-20250901-036', 'T-SS058-001', 'INSPECTION_REPORT',
       '2025-09-01'::DATE, 'Chris Anderson', 'TECH1698',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS058-001-20250901-036.pdf', 3841, 'PDF',
       'PREVENTIVE', 2.93, 11817.48,
       FALSE, 'Conducted scheduled preventive maintenance on T-SS058-001. Checked all electrical connections, found all secure. Oil level and color satisfactory. Bushings clean with no signs of tracking. Radiators clean and unobstructed. Load tap changer tested - operating normally. Recommended continued monitoring.', 'Conducted scheduled preventive maintenance on T-SS058-001. Checked all electrical connections, found all secure. Oil level and color satisfactory. Bushings clean with no signs of tracking. Radiators clean and unobstructed. Load tap changer tested - operating normally. Recommended continued monitoring.',
       PARSE_JSON('[]'), 'LOW',
       PARSE_JSON('["Sandblast and repaint", "Seal leaks", "Monitor corrosion rate", "Continue standard monitoring", "No immediate action required"]')
UNION ALL SELECT 'MAINT-T-SS011-001-20241227-037', 'T-SS011-001', 'INSPECTION_REPORT',
       '2024-12-27'::DATE, 'David Rodriguez', 'TECH8239',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS011-001-20241227-037.pdf', 3964, 'PDF',
       'CORRECTIVE', 10.98, 44977.25,
       FALSE, 'Responded to abnormal readings from T-SS011-001. Investigation revealed oil temp above 85°C. High Oil Temperature identified as primary issue. Performed clean radiators. Equipment returned to normal operation. Recommend follow-up inspection in 30 days to verify stability.', 'Responded to abnormal readings from T-SS011-001. Investigation revealed oil temp above 85°C. High Oil Temperature identified as primary issue. Performed clean radiators. Equipment returned to normal operation. Recommend follow-up inspection in 30 days to verify stability.',
       PARSE_JSON('["High Oil Temperature", "oil temp above 85\u00b0C", "radiator inefficiency"]'), 'HIGH',
       PARSE_JSON('["Clean radiators", "Check oil level", "Inspect cooling fans", "Increase monitoring frequency", "Schedule follow-up in 2 weeks", "Review similar assets"]')
UNION ALL SELECT 'MAINT-T-SS089-001-20240910-038', 'T-SS089-001', 'INSPECTION_REPORT',
       '2024-09-10'::DATE, 'Mike Chen', 'TECH1874',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS089-001-20240910-038.pdf', 3841, 'PDF',
       'EMERGENCY', 17.83, 43295.97,
       FALSE, 'Critical failure event on T-SS089-001. Operations detected high CO/CO2 ratio. Emergency shutdown initiated per safety protocol. Assessment revealed dissolved gas anomaly caused the outage. Backup power systems activated. Load reduction in progress. Coordinating with grid operations for load management. ETA to service restoration: 2-3 days.', 'Critical failure event on T-SS089-001. Operations detected high CO/CO2 ratio. Emergency shutdown initiated per safety protocol. Assessment revealed dissolved gas anomaly caused the outage. Backup power systems activated. Load reduction in progress. Coordinating with grid operations for load management. ETA to service restoration: 2-3 days.',
       PARSE_JSON('[]'), 'LOW',
       PARSE_JSON('["DGA analysis", "Load reduction", "Immediate inspection", "Continue standard monitoring", "No immediate action required"]')
UNION ALL SELECT 'MAINT-T-SS025-001-20250429-039', 'T-SS025-001', 'INSPECTION_REPORT',
       '2025-04-29'::DATE, 'Mike Chen', 'TECH3660',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS025-001-20250429-039.pdf', 3827, 'PDF',
       'PREVENTIVE', 2.52, 14400.96,
       FALSE, 'Performed routine quarterly inspection of transformer T-SS025-001. Visual inspection showed equipment in satisfactory condition. Oil sample collected for laboratory analysis. All cooling fans operational. Minor paint touch-up applied to tank exterior. No immediate concerns noted.', 'Performed routine quarterly inspection of transformer T-SS025-001. Visual inspection showed equipment in satisfactory condition. Oil sample collected for laboratory analysis. All cooling fans operational. Minor paint touch-up applied to tank exterior. No immediate concerns noted.',
       PARSE_JSON('[]'), 'LOW',
       PARSE_JSON('["Offline testing", "Bushing replacement", "Emergency repair", "Continue standard monitoring", "No immediate action required"]')
UNION ALL SELECT 'MAINT-T-SS007-001-20240227-040', 'T-SS007-001', 'INSPECTION_REPORT',
       '2024-02-27'::DATE, 'Chris Anderson', 'TECH4592',
       '@MAINTENANCE_DOCS_STAGE/MAINT-T-SS007-001-20240227-040.pdf', 3823, 'PDF',
       'PREVENTIVE', 2.5, 14529.4,
       FALSE, 'Performed routine quarterly inspection of transformer T-SS007-001. Visual inspection showed equipment in satisfactory condition. Oil sample collected for laboratory analysis. All cooling fans operational. Minor paint touch-up applied to tank exterior. No immediate concerns noted.', 'Performed routine quarterly inspection of transformer T-SS007-001. Visual inspection showed equipment in satisfactory condition. Oil sample collected for laboratory analysis. All cooling fans operational. Minor paint touch-up applied to tank exterior. No immediate concerns noted.',
       PARSE_JSON('[]'), 'LOW',
       PARSE_JSON('["Assess damage", "Dry out equipment", "Replace damaged parts", "Continue standard monitoring", "No immediate action required"]')
;
