USE DATABASE UTILITIES_GRID_RELIABILITY;
USE SCHEMA RAW;
USE WAREHOUSE GRID_RELIABILITY_WH;

-- Load Asset Master
PUT file://generated_data/asset_master.csv @ASSET_DATA_STAGE AUTO_COMPRESS=TRUE OVERWRITE=TRUE;

COPY INTO ASSET_MASTER FROM @ASSET_DATA_STAGE/asset_master.csv.gz
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('NULL', 'null', ''))
ON_ERROR = CONTINUE
PURGE = TRUE;

-- Load Sensor Readings (all batches)
PUT file://generated_data/sensor_readings_batch_*.json @SENSOR_DATA_STAGE AUTO_COMPRESS=TRUE OVERWRITE=TRUE;

COPY INTO SENSOR_READINGS FROM @SENSOR_DATA_STAGE/
FILE_FORMAT = (TYPE = JSON)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = CONTINUE
PURGE = TRUE;

-- Load Maintenance History
PUT file://generated_data/maintenance_history.csv @MAINTENANCE_DATA_STAGE AUTO_COMPRESS=TRUE OVERWRITE=TRUE;

COPY INTO MAINTENANCE_HISTORY FROM @MAINTENANCE_DATA_STAGE/maintenance_history.csv.gz
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('NULL', 'null', ''))
ON_ERROR = CONTINUE
PURGE = TRUE;

-- Load Failure Events
PUT file://generated_data/failure_events.csv @ASSET_DATA_STAGE AUTO_COMPRESS=TRUE OVERWRITE=TRUE;

COPY INTO FAILURE_EVENTS FROM @ASSET_DATA_STAGE/failure_events.csv.gz
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('NULL', 'null', ''))
ON_ERROR = CONTINUE
PURGE = TRUE;

-- Verify data loaded
SELECT 'ASSET_MASTER' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM ASSET_MASTER
UNION ALL
SELECT 'SENSOR_READINGS', COUNT(*) FROM SENSOR_READINGS
UNION ALL
SELECT 'MAINTENANCE_HISTORY', COUNT(*) FROM MAINTENANCE_HISTORY
UNION ALL
SELECT 'FAILURE_EVENTS', COUNT(*) FROM FAILURE_EVENTS;
